spring:
  application:
    name: user-center
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: czzeng.com:8848
        metadata:
          instance: zz
          version: 0.1
        namespace: ebdcf006-7ac0-4c4f-b8f5-743908b0b28f

management                                                                    :
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8013