spring:
  application:
    name: user-center
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.50.236:3306/user_center?serverTimezone=Asia/Shanghai
    username: root
    password: czroot

  cloud:
    nacos:
      discovery:
        server-addr: 101.200.50.236:8848
        metadata:
          instance: zz
          version: 0.1

management                                                                    :
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 8010

rocketmq:
  name-server: 101.200.50.236:9876

jwt:
  secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaddddddddddddd
  expire-time-in-second: 1209600