spring:
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 101.200.50.236:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=Asia/Shanghai
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always
server:
  port: 8003

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    clients: user-center
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    # feign的日志系统是建立在SpringBoot基础上的，此处一定要是debug, 否则都不会打印
    com.soft1851.content.center.feignclient.UserCenterFeignClient: debug

feign:
#  client:
#    config:
#      # 全局配置
#      default:
#        loggerLevel: full
  httpclient:
    # feign使用apache httpclient做请求; 而不是默认的url connection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50